#:schema node_modules/wrangler/config-schema.json
name = "hubspot-forms-slack-reporter"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

#[triggers]
#crons = ["0 6 * * *"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
